### ISSUE TITLE
Add the Fcfa currency in front of the salary field on the formular

### ISSUE THREAD

**Issue by elhmn** [osscameroon/camerdevs#104]

**Comment by Asam237** [comment]
Should I add this device in front of the text "Salary" ? 

![devicefcfa](https://user-images.githubusercontent.com/34966088/154892229-6a05d09b-7979-4783-9002-2031b70cddf1.png)

**Comment by elhmn** [comment]
> @elhmn Should I add this device in front of the text "Salary" ?
> 
> ![devicefcfa](https://user-images.githubusercontent.com/34966088/154892229-6a05d09b-7979-4783-9002-2031b70cddf1.png)

That's one for @Theryx

**Comment by Theryx** [comment]
I will suggest Salary (FCFA). 

Then when typing the amount there should be an automatic thousand separator or comma separation
