### ISSUE TITLE
Rename Preview word on the filters

### ISSUE THREAD

**Issue by Theryx** [osscameroon/camerdevs#135]
I think while we figure out how to make it clear at first sight we can rename the filter names to the actual field names and avoid using any as filter names

See image below
<img width="307" alt="image" src="https://user-images.githubusercontent.com/45546512/155892631-6b31d4e4-72ce-479b-8c38-14e3c1ed80b8.png">

What do you guys think?

**Comment by valerymelou** [comment]
Yeah I agree here. Created an issue but removed it when I saw you already created this one.
