### ISSUE TITLE
Add explicit labels or placeholders to filters

### ISSUE THREAD

**Issue by valerymelou** [osscameroon/camerdevs#136]
It's not clear what we are filtering against until we click on the dropdown to see the list of job titles or companies:
![image](https://user-images.githubusercontent.com/9080102/155892914-7e723a8f-3c3a-4d3a-89ba-aad4b32e24ca.png)

The filters should have explicit labels or placeholders inviting them to filter by job title or company.

**Comment by elhmn** [comment]
Oh I see why you closed it now 😄
