### ISSUE TITLE
Set Rating, Company name, Jobtitles as Mandatory field for the rating `POST` request

### ISSUE THREAD

**Issue by elhmn** [osscameroon/camerdevs#202]

**Comment by elhmn** [comment]
So now the `company_name` and the `ratings` are not mandatory anymore, but we should check for the cities. This change should ve reflected on #207

**Comment by DipandaAser** [comment]
> So now the `company_name` and the `ratings` are not mandatory anymore, but we should check for the cities. This change should ve reflected on #207

@elhmn  changes applied on #207
