### ISSUE TITLE
Update description on the home screen

### ISSUE THREAD

**Issue by Theryx** [osscameroon/camerdevs#214]
...But here is what you need to know:
* **The company name** is only displayed if at least 3 people in the same company with the same job title contribute. Until then, a generic description like "A local company" will be displayed.
* **The comment** is only displayed if at least 3 people in the same company with the same job title contribute.
* **The rating** is only displayed if at least 3 people in the same company with the same job title contribute.

**Comment by Zaker237** [comment]
@elhmn 

this PR is somehow confused, should we manage this in front or in backend??

**Comment by Theryx** [comment]
All descriptions are managed on the Frontend

**Comment by elhmn** [comment]
I updated the text in the description. 

I still don't feel comfortable leaving that 100% Anonymous text on the description. I it is a bold claim 😄

**Comment by Theryx** [comment]
> I updated the text in the description. 
> 
> I still don't feel comfortable leaving that 100% Anonymous text on the description. I it is a bold claim 😄 

I don't see the text.
Where is the update?

**Comment by elhmn** [comment]
> > I updated the text in the description.
> > I still don't feel comfortable leaving that 100% Anonymous text on the description. I it is a bold claim 😄
> 
> I don't see the text. Where is the update?

The text is in the description, I changed. I should have probably kept the previous version 🤦‍♂️

**Comment by elhmn** [comment]
You can see the different versions from here 👇 
![Screenshot 2022-04-24 at 12 07 24](https://user-images.githubusercontent.com/5704817/164971385-c650c75f-f264-4294-ba15-c17fe2a4b8f7.png)

**Comment by Theryx** [comment]
Alright I agree.
