### ISSUE TITLE
Update description of Company Name

### ISSUE THREAD

**Issue by Theryx** [osscameroon/camerdevs#215]
You are required to enter the name of the company. We understand you might not want to share the name of the company despite the field being anonymized- please enter a description of the company (e.g. "local startup", "well-known bank" or legacy company, etc)

**Comment by elhmn** [comment]
One thing in this comment is not true anymore. Here is the update I suggest.

```
We understand you might not want to share the name of the company despite the field being anonymized-please enter a description of the company (e.g. "local startup", "well-known bank" or legacy company, etc)
```

**Comment by Theryx** [comment]
> One thing in this comment is not true anymore. Here is the update I suggest.
> 
> ```
> We understand you might not want to share the name of the company despite the field being anonymized-please enter a description of the company (e.g. "local startup", "well-known bank" or legacy company, etc)
> ```

I don't see the changes or I'm not checking the right place?

Where are your updates @elhmn ?
