### ISSUE TITLE
Add rating detail

### ISSUE THREAD

**Issue by elhmn** [osscameroon/camerdevs#34]
We show a detail card to display more data about the salary/rating entry, generally a comment about the user experience in the company.

**Please refer to the figma design this is only an indication**
<img width="876" alt="Screenshot 2022-01-22 at 07 48 12" src="https://user-images.githubusercontent.com/5704817/150628746-23d1eb6b-8987-4e3e-8ab5-6ed5f69ae6c2.png">

**Comment by Asam237** [comment]
This issue has been done.

**Comment by Asam237** [comment]
This issue has been resolved here #41
