### ISSUE TITLE
show the current page and the total number of page and mobiles devices??

### ISSUE THREAD

**Issue by Zaker237** [osscameroon/camerdevs#91]
in the pagination component, when browsing the app from a mobile device, we can just go to the next or preview page. but in some ca when can have more than 100 page and for these case it can be a great idea for the user to known on which page he is.

**Comment by elhmn** [comment]
We should talk about it on a meeting, I suggest we have one this Friday. Does it work for you @Theryx ?

**Comment by elhmn** [comment]
Fixed by #132
